services:
  web:
    # Build the image from the Dockerfile in the current directory
    build: .

    # Host the FastAPI application on port 8000
    ports:
      - "8000:8000"

    volumes:
      - /Users/howard/Movies/Infuse:/app/downloads
